[Thu Aug 10 17:57:45.171450 2017] [:error] [pid 1677] [client 127.0.0.1:57358] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 65028096 bytes) in /var/www/html/laravel/admin/app/Providers/AuthServiceProvider.php on line 47
[Thu Aug 10 17:57:45.172446 2017] [:error] [pid 1677] [client 127.0.0.1:57358] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 65036288 bytes) in /var/www/html/laravel/admin/vendor/symfony/http-foundation/Response.php on line 371
[Thu Aug 10 17:57:45.172530 2017] [:error] [pid 1677] [client 127.0.0.1:57358] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 65015808 bytes) in Unknown on line 0
[Fri Aug 11 12:03:57.749386 2017] [:error] [pid 15409] [client 127.0.0.1:37978] PHP Fatal error:  Cannot use [] for reading in /var/www/html/laravel/admin/app/Http/Middleware/HasAccess.php on line 40, referer: http://localhost:3000/
[Fri Aug 11 12:04:04.057088 2017] [:error] [pid 3684] [client 127.0.0.1:37996] PHP Fatal error:  Cannot use [] for reading in /var/www/html/laravel/admin/app/Http/Middleware/HasAccess.php on line 40, referer: http://localhost:3000/
[Fri Aug 11 15:26:46.780135 2017] [:error] [pid 15407] [client 127.0.0.1:43940] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 65028096 bytes) in /var/www/html/laravel/admin/app/Http/Middleware/HasAccess.php on line 34
[Fri Aug 11 15:26:46.801278 2017] [:error] [pid 15407] [client 127.0.0.1:43940] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 65036288 bytes) in /var/www/html/laravel/admin/vendor/symfony/http-foundation/Response.php on line 371
[Fri Aug 11 15:27:16.795251 2017] [:error] [pid 15414] [client 127.0.0.1:43950] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 65028096 bytes) in /var/www/html/laravel/admin/app/Http/Middleware/HasAccess.php on line 34
[Fri Aug 11 15:27:16.796502 2017] [:error] [pid 15414] [client 127.0.0.1:43950] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 65036288 bytes) in /var/www/html/laravel/admin/vendor/symfony/http-foundation/Response.php on line 371
[Fri Aug 11 15:46:56.781876 2017] [:error] [pid 2770] [client 127.0.0.1:48322] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 99778560 bytes) in /var/www/html/laravel/admin/app/Http/Middleware/HasAccess.php on line 39
[Fri Aug 11 15:46:56.802678 2017] [:error] [pid 2770] [client 127.0.0.1:48322] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 99786752 bytes) in /var/www/html/laravel/admin/vendor/symfony/http-foundation/Response.php on line 371
[Fri Aug 11 15:46:56.802727 2017] [:error] [pid 2770] [client 127.0.0.1:48322] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 99762176 bytes) in Unknown on line 0
[Fri Aug 11 15:47:09.526015 2017] [:error] [pid 1593] [client 127.0.0.1:48332] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 66224128 bytes) in /var/www/html/laravel/admin/app/Http/Middleware/HasAccess.php on line 39
[Fri Aug 11 15:47:09.526763 2017] [:error] [pid 1593] [client 127.0.0.1:48332] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 66232320 bytes) in /var/www/html/laravel/admin/vendor/symfony/http-foundation/Response.php on line 371
[Fri Aug 11 15:47:09.526801 2017] [:error] [pid 1593] [client 127.0.0.1:48332] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 66207744 bytes) in Unknown on line 0
[Mon Aug 14 12:32:31.424098 2017] [:error] [pid 1574] [client 127.0.0.1:59272] PHP Fatal error:  Uncaught ErrorException: Undefined variable: request in /var/www/html/laravel/admin/app/Exceptions/Handler.php:36\nStack trace:\n#0 /var/www/html/laravel/admin/app/Exceptions/Handler.php(36): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined varia...', '/var/www/html/l...', 36, Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(80): App\\Exceptions\\Handler->report(Object(ErrorException))\n#2 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(ErrorException))\n#3 {main}\n  thrown in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 36
[Mon Aug 14 12:32:31.507645 2017] [:error] [pid 1574] [client 127.0.0.1:59272] PHP Fatal error:  Uncaught ErrorException: Undefined variable: request in /var/www/html/laravel/admin/app/Exceptions/Handler.php:36\nStack trace:\n#0 /var/www/html/laravel/admin/app/Exceptions/Handler.php(36): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined varia...', '/var/www/html/l...', 36, Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(80): App\\Exceptions\\Handler->report(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#4 {main}\n  thrown in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 36
[Mon Aug 14 12:32:40.801149 2017] [:error] [pid 1575] [client 127.0.0.1:59278] PHP Fatal error:  Uncaught ErrorException: Undefined variable: request in /var/www/html/laravel/admin/app/Exceptions/Handler.php:36\nStack trace:\n#0 /var/www/html/laravel/admin/app/Exceptions/Handler.php(36): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined varia...', '/var/www/html/l...', 36, Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(80): App\\Exceptions\\Handler->report(Object(ErrorException))\n#2 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(ErrorException))\n#3 {main}\n  thrown in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 36
[Mon Aug 14 12:32:40.801290 2017] [:error] [pid 1575] [client 127.0.0.1:59278] PHP Fatal error:  Uncaught ErrorException: Undefined variable: request in /var/www/html/laravel/admin/app/Exceptions/Handler.php:36\nStack trace:\n#0 /var/www/html/laravel/admin/app/Exceptions/Handler.php(36): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined varia...', '/var/www/html/l...', 36, Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(80): App\\Exceptions\\Handler->report(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#4 {main}\n  thrown in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 36
[Mon Aug 14 12:32:53.682713 2017] [:error] [pid 1576] [client 127.0.0.1:59284] PHP Fatal error:  Uncaught ErrorException: Undefined variable: request in /var/www/html/laravel/admin/app/Exceptions/Handler.php:36\nStack trace:\n#0 /var/www/html/laravel/admin/app/Exceptions/Handler.php(36): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined varia...', '/var/www/html/l...', 36, Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(80): App\\Exceptions\\Handler->report(Object(ErrorException))\n#2 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(ErrorException))\n#3 {main}\n  thrown in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 36
[Mon Aug 14 12:32:53.682933 2017] [:error] [pid 1576] [client 127.0.0.1:59284] PHP Fatal error:  Uncaught ErrorException: Undefined variable: request in /var/www/html/laravel/admin/app/Exceptions/Handler.php:36\nStack trace:\n#0 /var/www/html/laravel/admin/app/Exceptions/Handler.php(36): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined varia...', '/var/www/html/l...', 36, Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(80): App\\Exceptions\\Handler->report(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#4 {main}\n  thrown in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 36
[Mon Aug 14 12:32:54.556297 2017] [:error] [pid 1577] [client 127.0.0.1:59290] PHP Fatal error:  Uncaught ErrorException: Undefined variable: request in /var/www/html/laravel/admin/app/Exceptions/Handler.php:36\nStack trace:\n#0 /var/www/html/laravel/admin/app/Exceptions/Handler.php(36): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined varia...', '/var/www/html/l...', 36, Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(80): App\\Exceptions\\Handler->report(Object(ErrorException))\n#2 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(ErrorException))\n#3 {main}\n  thrown in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 36
[Mon Aug 14 12:32:54.556420 2017] [:error] [pid 1577] [client 127.0.0.1:59290] PHP Fatal error:  Uncaught ErrorException: Undefined variable: request in /var/www/html/laravel/admin/app/Exceptions/Handler.php:36\nStack trace:\n#0 /var/www/html/laravel/admin/app/Exceptions/Handler.php(36): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined varia...', '/var/www/html/l...', 36, Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(80): App\\Exceptions\\Handler->report(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#4 {main}\n  thrown in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 36
[Mon Aug 14 12:32:56.149976 2017] [:error] [pid 4702] [client 127.0.0.1:59296] PHP Fatal error:  Uncaught ErrorException: Undefined variable: request in /var/www/html/laravel/admin/app/Exceptions/Handler.php:36\nStack trace:\n#0 /var/www/html/laravel/admin/app/Exceptions/Handler.php(36): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined varia...', '/var/www/html/l...', 36, Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(80): App\\Exceptions\\Handler->report(Object(ErrorException))\n#2 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(ErrorException))\n#3 {main}\n  thrown in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 36
[Mon Aug 14 12:32:56.150164 2017] [:error] [pid 4702] [client 127.0.0.1:59296] PHP Fatal error:  Uncaught ErrorException: Undefined variable: request in /var/www/html/laravel/admin/app/Exceptions/Handler.php:36\nStack trace:\n#0 /var/www/html/laravel/admin/app/Exceptions/Handler.php(36): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined varia...', '/var/www/html/l...', 36, Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(80): App\\Exceptions\\Handler->report(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#4 {main}\n  thrown in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 36
[Mon Aug 14 12:37:29.518679 2017] [:error] [pid 1574] [client 127.0.0.1:59842] PHP Fatal error:  Uncaught InvalidArgumentException: Route [errors.defaultError] not defined. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:304\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/Redirector.php(154): Illuminate\\Routing\\UrlGenerator->route('errors.defaultE...', Array)\n#1 /var/www/html/laravel/admin/app/Exceptions/Handler.php(49): Illuminate\\Routing\\Redirector->route('errors.defaultE...')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))\n#3 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(InvalidArgumentException))\n#4 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(InvalidArg in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php on line 304
[Mon Aug 14 12:37:29.518932 2017] [:error] [pid 1574] [client 127.0.0.1:59842] PHP Fatal error:  Uncaught InvalidArgumentException: Route [errors.defaultError] not defined. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:304\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/Redirector.php(154): Illuminate\\Routing\\UrlGenerator->route('errors.defaultE...', Array)\n#1 /var/www/html/laravel/admin/app/Exceptions/Handler.php(49): Illuminate\\Routing\\Redirector->route('errors.defaultE...')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#4 /var/www/html/laravel/admin/vendor/laravel/fra in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php on line 304
[Mon Aug 14 12:37:33.579567 2017] [:error] [pid 1575] [client 127.0.0.1:59848] PHP Fatal error:  Uncaught InvalidArgumentException: Route [errors.defaultError] not defined. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:304\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/Redirector.php(154): Illuminate\\Routing\\UrlGenerator->route('errors.defaultE...', Array)\n#1 /var/www/html/laravel/admin/app/Exceptions/Handler.php(49): Illuminate\\Routing\\Redirector->route('errors.defaultE...')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))\n#3 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(InvalidArgumentException))\n#4 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(InvalidArg in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php on line 304
[Mon Aug 14 12:37:33.579830 2017] [:error] [pid 1575] [client 127.0.0.1:59848] PHP Fatal error:  Uncaught InvalidArgumentException: Route [errors.defaultError] not defined. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:304\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/Redirector.php(154): Illuminate\\Routing\\UrlGenerator->route('errors.defaultE...', Array)\n#1 /var/www/html/laravel/admin/app/Exceptions/Handler.php(49): Illuminate\\Routing\\Redirector->route('errors.defaultE...')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#4 /var/www/html/laravel/admin/vendor/laravel/fra in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php on line 304
[Mon Aug 14 12:37:34.557730 2017] [:error] [pid 1576] [client 127.0.0.1:59854] PHP Fatal error:  Uncaught InvalidArgumentException: Route [errors.defaultError] not defined. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:304\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/Redirector.php(154): Illuminate\\Routing\\UrlGenerator->route('errors.defaultE...', Array)\n#1 /var/www/html/laravel/admin/app/Exceptions/Handler.php(49): Illuminate\\Routing\\Redirector->route('errors.defaultE...')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))\n#3 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(InvalidArgumentException))\n#4 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(InvalidArg in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php on line 304
[Mon Aug 14 12:37:34.557937 2017] [:error] [pid 1576] [client 127.0.0.1:59854] PHP Fatal error:  Uncaught InvalidArgumentException: Route [errors.defaultError] not defined. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:304\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/Redirector.php(154): Illuminate\\Routing\\UrlGenerator->route('errors.defaultE...', Array)\n#1 /var/www/html/laravel/admin/app/Exceptions/Handler.php(49): Illuminate\\Routing\\Redirector->route('errors.defaultE...')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#4 /var/www/html/laravel/admin/vendor/laravel/fra in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php on line 304
[Mon Aug 14 12:37:56.789374 2017] [:error] [pid 1577] [client 127.0.0.1:59860] PHP Fatal error:  Uncaught InvalidArgumentException: Route [errors.defaultError] not defined. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:304\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/Redirector.php(154): Illuminate\\Routing\\UrlGenerator->route('errors.defaultE...', Array)\n#1 /var/www/html/laravel/admin/app/Exceptions/Handler.php(49): Illuminate\\Routing\\Redirector->route('errors.defaultE...')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))\n#3 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(InvalidArgumentException))\n#4 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(InvalidArg in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php on line 304
[Mon Aug 14 12:37:56.789603 2017] [:error] [pid 1577] [client 127.0.0.1:59860] PHP Fatal error:  Uncaught InvalidArgumentException: Route [errors.defaultError] not defined. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:304\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/Redirector.php(154): Illuminate\\Routing\\UrlGenerator->route('errors.defaultE...', Array)\n#1 /var/www/html/laravel/admin/app/Exceptions/Handler.php(49): Illuminate\\Routing\\Redirector->route('errors.defaultE...')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#4 /var/www/html/laravel/admin/vendor/laravel/fra in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php on line 304
[Mon Aug 14 12:40:31.713714 2017] [:error] [pid 4702] [client 127.0.0.1:59952] PHP Fatal error:  Declaration of App\\Exceptions\\Handler::render($request, Exception $exception, $code) must be compatible with Illuminate\\Contracts\\Debug\\ExceptionHandler::render($request, Exception $e) in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 9
[Mon Aug 14 12:40:31.713885 2017] [:error] [pid 4702] [client 127.0.0.1:59952] PHP Fatal error:  Uncaught ReflectionException: Class App\\Exceptions\\Handler does not exist in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Container/Container.php:729\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Container/Container.php(729): ReflectionClass->__construct('App\\\\Exceptions\\\\...')\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Container/Container.php(608): Illuminate\\Container\\Container->build('App\\\\Exceptions\\\\...')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\\Container\\Container->resolve('App\\\\Exceptions\\\\...', Array)\n#3 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(709): Illuminate\\Container\\Container->makeWith('App\\\\Exceptions\\\\...', Array)\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Container/Container.php(248): Illuminate\\Foundation\\Application->makeWith('App\\\\Exceptions\\\\...', Arra in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 729
[Mon Aug 14 12:40:32.645270 2017] [:error] [pid 1573] [client 127.0.0.1:59958] PHP Fatal error:  Declaration of App\\Exceptions\\Handler::render($request, Exception $exception, $code) must be compatible with Illuminate\\Contracts\\Debug\\ExceptionHandler::render($request, Exception $e) in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 9
[Mon Aug 14 12:40:32.645402 2017] [:error] [pid 1573] [client 127.0.0.1:59958] PHP Fatal error:  Uncaught ReflectionException: Class App\\Exceptions\\Handler does not exist in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Container/Container.php:729\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Container/Container.php(729): ReflectionClass->__construct('App\\\\Exceptions\\\\...')\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Container/Container.php(608): Illuminate\\Container\\Container->build('App\\\\Exceptions\\\\...')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\\Container\\Container->resolve('App\\\\Exceptions\\\\...', Array)\n#3 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(709): Illuminate\\Container\\Container->makeWith('App\\\\Exceptions\\\\...', Array)\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Container/Container.php(248): Illuminate\\Foundation\\Application->makeWith('App\\\\Exceptions\\\\...', Arra in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 729
[Mon Aug 14 12:40:56.604351 2017] [:error] [pid 1575] [client 127.0.0.1:59976] PHP Fatal error:  Declaration of App\\Exceptions\\Handler::render($request, Exception $exception, $code) must be compatible with Illuminate\\Contracts\\Debug\\ExceptionHandler::render($request, Exception $e) in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 9
[Mon Aug 14 12:40:56.604510 2017] [:error] [pid 1575] [client 127.0.0.1:59976] PHP Fatal error:  Uncaught ReflectionException: Class App\\Exceptions\\Handler does not exist in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Container/Container.php:729\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Container/Container.php(729): ReflectionClass->__construct('App\\\\Exceptions\\\\...')\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Container/Container.php(608): Illuminate\\Container\\Container->build('App\\\\Exceptions\\\\...')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\\Container\\Container->resolve('App\\\\Exceptions\\\\...', Array)\n#3 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(709): Illuminate\\Container\\Container->makeWith('App\\\\Exceptions\\\\...', Array)\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Container/Container.php(248): Illuminate\\Foundation\\Application->makeWith('App\\\\Exceptions\\\\...', Arra in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 729
[Mon Aug 14 12:40:58.396222 2017] [:error] [pid 1576] [client 127.0.0.1:59982] PHP Fatal error:  Declaration of App\\Exceptions\\Handler::render($request, Exception $exception, $code) must be compatible with Illuminate\\Contracts\\Debug\\ExceptionHandler::render($request, Exception $e) in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 9
[Mon Aug 14 12:40:58.396376 2017] [:error] [pid 1576] [client 127.0.0.1:59982] PHP Fatal error:  Uncaught ReflectionException: Class App\\Exceptions\\Handler does not exist in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Container/Container.php:729\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Container/Container.php(729): ReflectionClass->__construct('App\\\\Exceptions\\\\...')\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Container/Container.php(608): Illuminate\\Container\\Container->build('App\\\\Exceptions\\\\...')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\\Container\\Container->resolve('App\\\\Exceptions\\\\...', Array)\n#3 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(709): Illuminate\\Container\\Container->makeWith('App\\\\Exceptions\\\\...', Array)\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Container/Container.php(248): Illuminate\\Foundation\\Application->makeWith('App\\\\Exceptions\\\\...', Arra in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 729
[Mon Aug 14 12:43:07.713301 2017] [:error] [pid 4702] [client 127.0.0.1:60004] PHP Fatal error:  Uncaught Error: Class 'App\\Exceptions\\HttpException' not found in /var/www/html/laravel/admin/app/Exceptions/Handler.php:48\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#2 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#3 {main}\n  thrown in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 48
[Mon Aug 14 12:43:07.713466 2017] [:error] [pid 4702] [client 127.0.0.1:60004] PHP Fatal error:  Uncaught Error: Class 'App\\Exceptions\\HttpException' not found in /var/www/html/laravel/admin/app/Exceptions/Handler.php:48\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#4 {main}\n  thrown in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 48
[Mon Aug 14 12:43:10.962462 2017] [:error] [pid 1573] [client 127.0.0.1:60010] PHP Fatal error:  Uncaught Error: Class 'App\\Exceptions\\HttpException' not found in /var/www/html/laravel/admin/app/Exceptions/Handler.php:48\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#2 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#3 {main}\n  thrown in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 48
[Mon Aug 14 12:43:10.962643 2017] [:error] [pid 1573] [client 127.0.0.1:60010] PHP Fatal error:  Uncaught Error: Class 'App\\Exceptions\\HttpException' not found in /var/www/html/laravel/admin/app/Exceptions/Handler.php:48\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#4 {main}\n  thrown in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 48
[Mon Aug 14 12:43:18.075426 2017] [:error] [pid 1574] [client 127.0.0.1:60016] PHP Fatal error:  Uncaught Error: Class 'App\\Exceptions\\HttpException' not found in /var/www/html/laravel/admin/app/Exceptions/Handler.php:48\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#2 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#3 {main}\n  thrown in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 48
[Mon Aug 14 12:43:18.075617 2017] [:error] [pid 1574] [client 127.0.0.1:60016] PHP Fatal error:  Uncaught Error: Class 'App\\Exceptions\\HttpException' not found in /var/www/html/laravel/admin/app/Exceptions/Handler.php:48\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#4 {main}\n  thrown in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 48
[Mon Aug 14 12:43:56.140669 2017] [:error] [pid 1575] [client 127.0.0.1:60040] PHP Fatal error:  Uncaught Error: Class 'App\\Exceptions\\HttpException' not found in /var/www/html/laravel/admin/app/Exceptions/Handler.php:48\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#2 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#3 {main}\n  thrown in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 48
[Mon Aug 14 12:43:56.140904 2017] [:error] [pid 1575] [client 127.0.0.1:60040] PHP Fatal error:  Uncaught Error: Class 'App\\Exceptions\\HttpException' not found in /var/www/html/laravel/admin/app/Exceptions/Handler.php:48\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#4 {main}\n  thrown in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 48
[Mon Aug 14 12:43:57.279903 2017] [:error] [pid 1576] [client 127.0.0.1:60046] PHP Fatal error:  Uncaught Error: Class 'App\\Exceptions\\HttpException' not found in /var/www/html/laravel/admin/app/Exceptions/Handler.php:48\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#2 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#3 {main}\n  thrown in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 48
[Mon Aug 14 12:43:57.280103 2017] [:error] [pid 1576] [client 127.0.0.1:60046] PHP Fatal error:  Uncaught Error: Class 'App\\Exceptions\\HttpException' not found in /var/www/html/laravel/admin/app/Exceptions/Handler.php:48\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#4 {main}\n  thrown in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 48
[Mon Aug 14 12:44:42.310232 2017] [:error] [pid 4702] [client 127.0.0.1:60074] PHP Fatal error:  Uncaught InvalidArgumentException: View [errors.500] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('errors.500', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('errors.500')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(69): Illuminate\\View\\Factory->make('errors.500', Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(53): Illuminate\\Routing\\ResponseFactory->view('errors.500', Array, 500)\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))\n#5 /var/www/html/laravel/admin/vendo in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 12:44:42.310672 2017] [:error] [pid 4702] [client 127.0.0.1:60074] PHP Fatal error:  Uncaught InvalidArgumentException: View [errors.500] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('errors.500', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('errors.500')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(69): Illuminate\\View\\Factory->make('errors.500', Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(53): Illuminate\\Routing\\ResponseFactory->view('errors.500', Array, 500)\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#5 /var in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 12:44:43.954966 2017] [:error] [pid 1573] [client 127.0.0.1:60080] PHP Fatal error:  Uncaught InvalidArgumentException: View [errors.500] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('errors.500', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('errors.500')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(69): Illuminate\\View\\Factory->make('errors.500', Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(53): Illuminate\\Routing\\ResponseFactory->view('errors.500', Array, 500)\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))\n#5 /var/www/html/laravel/admin/vendo in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 12:44:43.955233 2017] [:error] [pid 1573] [client 127.0.0.1:60080] PHP Fatal error:  Uncaught InvalidArgumentException: View [errors.500] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('errors.500', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('errors.500')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(69): Illuminate\\View\\Factory->make('errors.500', Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(53): Illuminate\\Routing\\ResponseFactory->view('errors.500', Array, 500)\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#5 /var in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 12:45:56.931255 2017] [:error] [pid 1574] [client 127.0.0.1:60088] PHP Fatal error:  Uncaught InvalidArgumentException: View [errors.500] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('errors.500', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('errors.500')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(69): Illuminate\\View\\Factory->make('errors.500', Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(56): Illuminate\\Routing\\ResponseFactory->view('errors.500', Array, 500)\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))\n#5 /var/www/html/laravel/admin/vendo in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 12:45:56.931569 2017] [:error] [pid 1574] [client 127.0.0.1:60088] PHP Fatal error:  Uncaught InvalidArgumentException: View [errors.500] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('errors.500', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('errors.500')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(69): Illuminate\\View\\Factory->make('errors.500', Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(56): Illuminate\\Routing\\ResponseFactory->view('errors.500', Array, 500)\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#5 /var in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 12:46:11.346494 2017] [:error] [pid 1575] [client 127.0.0.1:60094] PHP Fatal error:  Uncaught InvalidArgumentException: View [errors.403] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('errors.403', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('errors.403')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(69): Illuminate\\View\\Factory->make('errors.403', Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(56): Illuminate\\Routing\\ResponseFactory->view('errors.403', Array, 403)\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))\n#5 /var/www/html/laravel/admin/vendo in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 12:46:11.346768 2017] [:error] [pid 1575] [client 127.0.0.1:60094] PHP Fatal error:  Uncaught InvalidArgumentException: View [errors.403] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('errors.403', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('errors.403')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(69): Illuminate\\View\\Factory->make('errors.403', Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(56): Illuminate\\Routing\\ResponseFactory->view('errors.403', Array, 403)\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#5 /var in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 12:46:12.278796 2017] [:error] [pid 1576] [client 127.0.0.1:60100] PHP Fatal error:  Uncaught InvalidArgumentException: View [errors.403] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('errors.403', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('errors.403')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(69): Illuminate\\View\\Factory->make('errors.403', Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(56): Illuminate\\Routing\\ResponseFactory->view('errors.403', Array, 403)\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))\n#5 /var/www/html/laravel/admin/vendo in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 12:46:12.279016 2017] [:error] [pid 1576] [client 127.0.0.1:60100] PHP Fatal error:  Uncaught InvalidArgumentException: View [errors.403] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('errors.403', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('errors.403')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(69): Illuminate\\View\\Factory->make('errors.403', Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(56): Illuminate\\Routing\\ResponseFactory->view('errors.403', Array, 403)\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#5 /var in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 12:46:12.909048 2017] [:error] [pid 1577] [client 127.0.0.1:60106] PHP Fatal error:  Uncaught InvalidArgumentException: View [errors.403] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('errors.403', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('errors.403')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(69): Illuminate\\View\\Factory->make('errors.403', Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(56): Illuminate\\Routing\\ResponseFactory->view('errors.403', Array, 403)\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))\n#5 /var/www/html/laravel/admin/vendo in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 12:46:12.909512 2017] [:error] [pid 1577] [client 127.0.0.1:60106] PHP Fatal error:  Uncaught InvalidArgumentException: View [errors.403] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('errors.403', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('errors.403')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(69): Illuminate\\View\\Factory->make('errors.403', Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(56): Illuminate\\Routing\\ResponseFactory->view('errors.403', Array, 403)\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#5 /var in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 12:47:30.121462 2017] [:error] [pid 4702] [client 127.0.0.1:60114] PHP Fatal error:  Uncaught ErrorException: Undefined variable: e in /var/www/html/laravel/admin/app/Exceptions/Handler.php:57\nStack trace:\n#0 /var/www/html/laravel/admin/app/Exceptions/Handler.php(57): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined varia...', '/var/www/html/l...', 57, Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(ErrorException))\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(ErrorException))\n#3 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(ErrorException))\n#4 {main}\n  thrown in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 57
[Mon Aug 14 12:47:30.121683 2017] [:error] [pid 4702] [client 127.0.0.1:60114] PHP Fatal error:  Uncaught ErrorException: Undefined variable: e in /var/www/html/laravel/admin/app/Exceptions/Handler.php:57\nStack trace:\n#0 /var/www/html/laravel/admin/app/Exceptions/Handler.php(57): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined varia...', '/var/www/html/l...', 57, Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exceptio in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 57
[Mon Aug 14 12:48:02.204677 2017] [:error] [pid 1573] [client 127.0.0.1:60124] PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\\Component\\Debug\\Exception\\FatalThrowableError::getStatusCode() in /var/www/html/laravel/admin/app/Exceptions/Handler.php:57\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#2 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#3 {main}\n  thrown in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 57
[Mon Aug 14 12:48:02.204846 2017] [:error] [pid 1573] [client 127.0.0.1:60124] PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\\Component\\Debug\\Exception\\FatalErrorException::getStatusCode() in /var/www/html/laravel/admin/app/Exceptions/Handler.php:57\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#4  in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 57
[Mon Aug 14 12:53:21.365977 2017] [:error] [pid 1574] [client 127.0.0.1:60632] PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\\Component\\Debug\\Exception\\FatalThrowableError::getStatusCode() in /var/www/html/laravel/admin/app/Exceptions/Handler.php:57\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#2 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#3 {main}\n  thrown in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 57
[Mon Aug 14 12:53:21.366178 2017] [:error] [pid 1574] [client 127.0.0.1:60632] PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\\Component\\Debug\\Exception\\FatalErrorException::getStatusCode() in /var/www/html/laravel/admin/app/Exceptions/Handler.php:57\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#4  in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 57
[Mon Aug 14 12:53:30.930976 2017] [:error] [pid 1575] [client 127.0.0.1:60638] PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\\Component\\Debug\\Exception\\FatalThrowableError::getStatusCode() in /var/www/html/laravel/admin/app/Exceptions/Handler.php:57\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#2 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#3 {main}\n  thrown in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 57
[Mon Aug 14 12:53:30.931186 2017] [:error] [pid 1575] [client 127.0.0.1:60638] PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\\Component\\Debug\\Exception\\FatalErrorException::getStatusCode() in /var/www/html/laravel/admin/app/Exceptions/Handler.php:57\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#4  in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 57
[Mon Aug 14 12:53:31.782148 2017] [:error] [pid 1576] [client 127.0.0.1:60646] PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\\Component\\Debug\\Exception\\FatalThrowableError::getStatusCode() in /var/www/html/laravel/admin/app/Exceptions/Handler.php:57\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#2 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#3 {main}\n  thrown in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 57
[Mon Aug 14 12:53:31.782447 2017] [:error] [pid 1576] [client 127.0.0.1:60646] PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\\Component\\Debug\\Exception\\FatalErrorException::getStatusCode() in /var/www/html/laravel/admin/app/Exceptions/Handler.php:57\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#4  in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 57
[Mon Aug 14 12:54:11.931231 2017] [:error] [pid 1577] [client 127.0.0.1:60924] PHP Fatal error:  Uncaught InvalidArgumentException: Route [500] not defined. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:304\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(705): Illuminate\\Routing\\UrlGenerator->route('500', Array, true)\n#1 /var/www/html/laravel/admin/app/Exceptions/Handler.php(59): route('500')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))\n#3 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(InvalidArgumentException))\n#4 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(InvalidArgumentException))\n#5 {main}\n  thrown in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php on line 304
[Mon Aug 14 12:54:11.931512 2017] [:error] [pid 1577] [client 127.0.0.1:60924] PHP Fatal error:  Uncaught InvalidArgumentException: Route [500] not defined. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:304\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(705): Illuminate\\Routing\\UrlGenerator->route('500', Array, true)\n#1 /var/www/html/laravel/admin/app/Exceptions/Handler.php(59): route('500')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): I in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php on line 304
[Mon Aug 14 12:54:13.538679 2017] [:error] [pid 4702] [client 127.0.0.1:60932] PHP Fatal error:  Uncaught InvalidArgumentException: Route [500] not defined. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:304\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(705): Illuminate\\Routing\\UrlGenerator->route('500', Array, true)\n#1 /var/www/html/laravel/admin/app/Exceptions/Handler.php(59): route('500')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))\n#3 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(InvalidArgumentException))\n#4 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(InvalidArgumentException))\n#5 {main}\n  thrown in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php on line 304
[Mon Aug 14 12:54:13.539015 2017] [:error] [pid 4702] [client 127.0.0.1:60932] PHP Fatal error:  Uncaught InvalidArgumentException: Route [500] not defined. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:304\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(705): Illuminate\\Routing\\UrlGenerator->route('500', Array, true)\n#1 /var/www/html/laravel/admin/app/Exceptions/Handler.php(59): route('500')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): I in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php on line 304
[Mon Aug 14 12:54:47.333016 2017] [:error] [pid 1573] [client 127.0.0.1:60942] PHP Fatal error:  Uncaught Error: Class 'App\\Exceptions\\Response' not found in /var/www/html/laravel/admin/app/Exceptions/Handler.php:61\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#2 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#3 {main}\n  thrown in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 61
[Mon Aug 14 12:54:47.333224 2017] [:error] [pid 1573] [client 127.0.0.1:60942] PHP Fatal error:  Uncaught Error: Class 'App\\Exceptions\\Response' not found in /var/www/html/laravel/admin/app/Exceptions/Handler.php:61\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#4 {main}\n  thrown in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 61
[Mon Aug 14 12:54:48.363798 2017] [:error] [pid 1574] [client 127.0.0.1:60948] PHP Fatal error:  Uncaught Error: Class 'App\\Exceptions\\Response' not found in /var/www/html/laravel/admin/app/Exceptions/Handler.php:61\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#2 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#3 {main}\n  thrown in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 61
[Mon Aug 14 12:54:48.364031 2017] [:error] [pid 1574] [client 127.0.0.1:60948] PHP Fatal error:  Uncaught Error: Class 'App\\Exceptions\\Response' not found in /var/www/html/laravel/admin/app/Exceptions/Handler.php:61\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#4 {main}\n  thrown in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 61
[Mon Aug 14 12:54:58.737099 2017] [:error] [pid 1575] [client 127.0.0.1:60954] PHP Fatal error:  Uncaught Error: Class 'App\\Exceptions\\Response' not found in /var/www/html/laravel/admin/app/Exceptions/Handler.php:61\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#2 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#3 {main}\n  thrown in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 61
[Mon Aug 14 12:54:58.737259 2017] [:error] [pid 1575] [client 127.0.0.1:60954] PHP Fatal error:  Uncaught Error: Class 'App\\Exceptions\\Response' not found in /var/www/html/laravel/admin/app/Exceptions/Handler.php:61\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#4 {main}\n  thrown in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 61
[Mon Aug 14 12:54:59.615006 2017] [:error] [pid 1576] [client 127.0.0.1:60960] PHP Fatal error:  Uncaught Error: Class 'App\\Exceptions\\Response' not found in /var/www/html/laravel/admin/app/Exceptions/Handler.php:61\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#2 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#3 {main}\n  thrown in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 61
[Mon Aug 14 12:54:59.615221 2017] [:error] [pid 1576] [client 127.0.0.1:60960] PHP Fatal error:  Uncaught Error: Class 'App\\Exceptions\\Response' not found in /var/www/html/laravel/admin/app/Exceptions/Handler.php:61\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#4 {main}\n  thrown in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 61
[Mon Aug 14 12:55:00.469451 2017] [:error] [pid 1577] [client 127.0.0.1:60966] PHP Fatal error:  Uncaught Error: Class 'App\\Exceptions\\Response' not found in /var/www/html/laravel/admin/app/Exceptions/Handler.php:61\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#2 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#3 {main}\n  thrown in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 61
[Mon Aug 14 12:55:00.469904 2017] [:error] [pid 1577] [client 127.0.0.1:60966] PHP Fatal error:  Uncaught Error: Class 'App\\Exceptions\\Response' not found in /var/www/html/laravel/admin/app/Exceptions/Handler.php:61\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#4 {main}\n  thrown in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 61
[Mon Aug 14 12:57:12.231964 2017] [:error] [pid 1576] [client 127.0.0.1:32792] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Illuminate\\Foundation\\Exceptions\\Handler::convertExceptionToResponse() must be an instance of Exception, none given, called in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 47 and defined in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:207\nStack trace:\n#0 /var/www/html/laravel/admin/app/Exceptions/Handler.php(47): Illuminate\\Foundation\\Exceptions\\Handler->convertExceptionToResponse()\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#3 [internal function]: Il in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php on line 207
[Mon Aug 14 12:57:12.232274 2017] [:error] [pid 1576] [client 127.0.0.1:32792] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Illuminate\\Foundation\\Exceptions\\Handler::convertExceptionToResponse() must be an instance of Exception, none given, called in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 47 and defined in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:207\nStack trace:\n#0 /var/www/html/laravel/admin/app/Exceptions/Handler.php(47): Illuminate\\Foundation\\Exceptions\\Handler->convertExceptionToResponse()\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 /var/www/html/laravel/a in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php on line 207
[Mon Aug 14 12:57:15.586777 2017] [:error] [pid 1577] [client 127.0.0.1:32798] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Illuminate\\Foundation\\Exceptions\\Handler::convertExceptionToResponse() must be an instance of Exception, none given, called in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 47 and defined in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:207\nStack trace:\n#0 /var/www/html/laravel/admin/app/Exceptions/Handler.php(47): Illuminate\\Foundation\\Exceptions\\Handler->convertExceptionToResponse()\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#3 [internal function]: Il in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php on line 207
[Mon Aug 14 12:57:15.586966 2017] [:error] [pid 1577] [client 127.0.0.1:32798] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Illuminate\\Foundation\\Exceptions\\Handler::convertExceptionToResponse() must be an instance of Exception, none given, called in /var/www/html/laravel/admin/app/Exceptions/Handler.php on line 47 and defined in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:207\nStack trace:\n#0 /var/www/html/laravel/admin/app/Exceptions/Handler.php(47): Illuminate\\Foundation\\Exceptions\\Handler->convertExceptionToResponse()\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 /var/www/html/laravel/a in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php on line 207
[Mon Aug 14 12:58:14.565396 2017] [:error] [pid 1575] [client 127.0.0.1:32838] PHP Fatal error:  Uncaught InvalidArgumentException: View [errors.500] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('errors.500', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('errors.500')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(881): Illuminate\\View\\Factory->make('errors.500', Array, Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(49): view('errors.500')\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))\n#5 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 12:58:14.565665 2017] [:error] [pid 1575] [client 127.0.0.1:32838] PHP Fatal error:  Uncaught InvalidArgumentException: View [errors.500] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('errors.500', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('errors.500')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(881): Illuminate\\View\\Factory->make('errors.500', Array, Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(49): view('errors.500')\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#5 /var/www/html/laravel/admin/vendor/laravel/framew in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 12:58:17.659942 2017] [:error] [pid 1576] [client 127.0.0.1:32844] PHP Fatal error:  Uncaught InvalidArgumentException: View [errors.500] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('errors.500', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('errors.500')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(881): Illuminate\\View\\Factory->make('errors.500', Array, Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(49): view('errors.500')\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))\n#5 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 12:58:17.660213 2017] [:error] [pid 1576] [client 127.0.0.1:32844] PHP Fatal error:  Uncaught InvalidArgumentException: View [errors.500] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('errors.500', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('errors.500')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(881): Illuminate\\View\\Factory->make('errors.500', Array, Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(49): view('errors.500')\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#5 /var/www/html/laravel/admin/vendor/laravel/framew in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 12:58:21.185091 2017] [:error] [pid 1577] [client 127.0.0.1:32850] PHP Fatal error:  Uncaught InvalidArgumentException: View [errors.500] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('errors.500', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('errors.500')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(881): Illuminate\\View\\Factory->make('errors.500', Array, Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(49): view('errors.500')\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))\n#5 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 12:58:21.185367 2017] [:error] [pid 1577] [client 127.0.0.1:32850] PHP Fatal error:  Uncaught InvalidArgumentException: View [errors.500] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('errors.500', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('errors.500')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(881): Illuminate\\View\\Factory->make('errors.500', Array, Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(49): view('errors.500')\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#5 /var/www/html/laravel/admin/vendor/laravel/framew in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 12:58:39.817429 2017] [:error] [pid 4702] [client 127.0.0.1:32858] PHP Fatal error:  Uncaught InvalidArgumentException: View [login] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('login', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('login')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(881): Illuminate\\View\\Factory->make('login', Array, Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(49): view('login')\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))\n#5 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptio in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 12:58:39.817677 2017] [:error] [pid 4702] [client 127.0.0.1:32858] PHP Fatal error:  Uncaught InvalidArgumentException: View [login] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('login', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('login')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(881): Illuminate\\View\\Factory->make('login', Array, Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(49): view('login')\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#5 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Founda in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 12:58:41.561004 2017] [:error] [pid 1573] [client 127.0.0.1:32864] PHP Fatal error:  Uncaught InvalidArgumentException: View [login] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('login', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('login')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(881): Illuminate\\View\\Factory->make('login', Array, Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(49): view('login')\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))\n#5 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptio in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 12:58:41.561235 2017] [:error] [pid 1573] [client 127.0.0.1:32864] PHP Fatal error:  Uncaught InvalidArgumentException: View [login] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('login', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('login')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(881): Illuminate\\View\\Factory->make('login', Array, Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(49): view('login')\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#5 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Founda in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 12:58:44.437499 2017] [:error] [pid 1574] [client 127.0.0.1:32870] PHP Fatal error:  Uncaught InvalidArgumentException: View [login] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('login', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('login')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(881): Illuminate\\View\\Factory->make('login', Array, Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(49): view('login')\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))\n#5 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptio in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 12:58:44.437742 2017] [:error] [pid 1574] [client 127.0.0.1:32870] PHP Fatal error:  Uncaught InvalidArgumentException: View [login] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('login', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('login')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(881): Illuminate\\View\\Factory->make('login', Array, Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(49): view('login')\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#5 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Founda in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 12:58:47.047268 2017] [:error] [pid 1575] [client 127.0.0.1:32876] PHP Fatal error:  Uncaught InvalidArgumentException: View [login] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('login', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('login')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(881): Illuminate\\View\\Factory->make('login', Array, Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(49): view('login')\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))\n#5 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptio in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 12:58:47.047622 2017] [:error] [pid 1575] [client 127.0.0.1:32876] PHP Fatal error:  Uncaught InvalidArgumentException: View [login] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('login', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('login')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(881): Illuminate\\View\\Factory->make('login', Array, Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(49): view('login')\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#5 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Founda in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 12:59:13.996123 2017] [:error] [pid 1573] [client 127.0.0.1:33008] PHP Fatal error:  Uncaught InvalidArgumentException: Route [teste] not defined. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:304\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(705): Illuminate\\Routing\\UrlGenerator->route('teste', Array, true)\n#1 /var/www/html/laravel/admin/app/Exceptions/Handler.php(49): route('teste')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))\n#3 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(InvalidArgumentException))\n#4 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(InvalidArgumentException))\n#5 {main}\n  thrown in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php on line 304
[Mon Aug 14 12:59:13.996365 2017] [:error] [pid 1573] [client 127.0.0.1:33008] PHP Fatal error:  Uncaught InvalidArgumentException: Route [teste] not defined. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:304\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(705): Illuminate\\Routing\\UrlGenerator->route('teste', Array, true)\n#1 /var/www/html/laravel/admin/app/Exceptions/Handler.php(49): route('teste')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(1 in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php on line 304
[Mon Aug 14 13:00:01.900384 2017] [:error] [pid 1574] [client 127.0.0.1:33018] PHP Fatal error:  Uncaught InvalidArgumentException: View [errors.404] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('errors.404', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('errors.404')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(69): Illuminate\\View\\Factory->make('errors.404', Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(51): Illuminate\\Routing\\ResponseFactory->view('errors.404', Array, 404)\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))\n#5 /var/www/html/laravel/admin/vendo in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 13:00:01.900696 2017] [:error] [pid 1574] [client 127.0.0.1:33018] PHP Fatal error:  Uncaught InvalidArgumentException: View [errors.404] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('errors.404', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('errors.404')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(69): Illuminate\\View\\Factory->make('errors.404', Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(51): Illuminate\\Routing\\ResponseFactory->view('errors.404', Array, 404)\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#5 /var in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 13:00:03.137936 2017] [:error] [pid 1575] [client 127.0.0.1:33024] PHP Fatal error:  Uncaught InvalidArgumentException: View [errors.404] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('errors.404', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('errors.404')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(69): Illuminate\\View\\Factory->make('errors.404', Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(51): Illuminate\\Routing\\ResponseFactory->view('errors.404', Array, 404)\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))\n#5 /var/www/html/laravel/admin/vendo in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 13:00:03.138162 2017] [:error] [pid 1575] [client 127.0.0.1:33024] PHP Fatal error:  Uncaught InvalidArgumentException: View [errors.404] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('errors.404', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('errors.404')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(69): Illuminate\\View\\Factory->make('errors.404', Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(51): Illuminate\\Routing\\ResponseFactory->view('errors.404', Array, 404)\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#5 /var in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 13:00:07.136582 2017] [:error] [pid 1576] [client 127.0.0.1:33030] PHP Fatal error:  Uncaught InvalidArgumentException: View [errors.404] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('errors.404', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('errors.404')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(69): Illuminate\\View\\Factory->make('errors.404', Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(51): Illuminate\\Routing\\ResponseFactory->view('errors.404', Array, 404)\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))\n#5 /var/www/html/laravel/admin/vendo in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 13:00:07.136818 2017] [:error] [pid 1576] [client 127.0.0.1:33030] PHP Fatal error:  Uncaught InvalidArgumentException: View [errors.404] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('errors.404', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('errors.404')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(69): Illuminate\\View\\Factory->make('errors.404', Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(51): Illuminate\\Routing\\ResponseFactory->view('errors.404', Array, 404)\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#5 /var in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 13:00:08.201581 2017] [:error] [pid 1577] [client 127.0.0.1:33036] PHP Fatal error:  Uncaught InvalidArgumentException: View [errors.404] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('errors.404', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('errors.404')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(69): Illuminate\\View\\Factory->make('errors.404', Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(51): Illuminate\\Routing\\ResponseFactory->view('errors.404', Array, 404)\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))\n#5 /var/www/html/laravel/admin/vendo in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 13:00:08.201824 2017] [:error] [pid 1577] [client 127.0.0.1:33036] PHP Fatal error:  Uncaught InvalidArgumentException: View [errors.404] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('errors.404', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('errors.404')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(69): Illuminate\\View\\Factory->make('errors.404', Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(51): Illuminate\\Routing\\ResponseFactory->view('errors.404', Array, 404)\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#5 /var in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 13:00:19.607372 2017] [:error] [pid 4702] [client 127.0.0.1:33042] PHP Fatal error:  Uncaught InvalidArgumentException: View [login] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('login', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('login')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(69): Illuminate\\View\\Factory->make('login', Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(51): Illuminate\\Routing\\ResponseFactory->view('login', Array, 404)\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))\n#5 /var/www/html/laravel/admin/vendor/laravel/framework/src/I in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 13:00:19.607610 2017] [:error] [pid 4702] [client 127.0.0.1:33042] PHP Fatal error:  Uncaught InvalidArgumentException: View [login] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('login', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('login')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(69): Illuminate\\View\\Factory->make('login', Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(51): Illuminate\\Routing\\ResponseFactory->view('login', Array, 404)\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#5 /var/www/html/laravel/admin/v in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 13:00:20.406147 2017] [:error] [pid 1573] [client 127.0.0.1:33048] PHP Fatal error:  Uncaught InvalidArgumentException: View [login] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('login', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('login')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(69): Illuminate\\View\\Factory->make('login', Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(51): Illuminate\\Routing\\ResponseFactory->view('login', Array, 404)\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))\n#5 /var/www/html/laravel/admin/vendor/laravel/framework/src/I in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 13:00:20.406719 2017] [:error] [pid 1573] [client 127.0.0.1:33048] PHP Fatal error:  Uncaught InvalidArgumentException: View [login] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('login', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('login')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(69): Illuminate\\View\\Factory->make('login', Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(51): Illuminate\\Routing\\ResponseFactory->view('login', Array, 404)\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#5 /var/www/html/laravel/admin/v in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 13:00:30.395279 2017] [:error] [pid 1574] [client 127.0.0.1:33054] PHP Fatal error:  Uncaught InvalidArgumentException: View [login] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('login', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('login')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(69): Illuminate\\View\\Factory->make('login', Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(51): Illuminate\\Routing\\ResponseFactory->view('login', Array, 'login')\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))\n#5 /var/www/html/laravel/admin/vendor/laravel/framework/s in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 13:00:30.395799 2017] [:error] [pid 1574] [client 127.0.0.1:33054] PHP Fatal error:  Uncaught InvalidArgumentException: View [login] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('login', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('login')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(69): Illuminate\\View\\Factory->make('login', Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(51): Illuminate\\Routing\\ResponseFactory->view('login', Array, 'login')\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#5 /var/www/html/laravel/adm in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 13:03:33.463832 2017] [:error] [pid 1575] [client 127.0.0.1:33228] PHP Fatal error:  Uncaught InvalidArgumentException: View [errors.custom] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('errors.custom', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('errors.custom')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(69): Illuminate\\View\\Factory->make('errors.custom', Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(49): Illuminate\\Routing\\ResponseFactory->view('errors.custom', Array, 403)\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))\n#5 /var/www/html/lara in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 13:03:33.464089 2017] [:error] [pid 1575] [client 127.0.0.1:33228] PHP Fatal error:  Uncaught InvalidArgumentException: View [errors.custom] not found. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('errors.custom', Array)\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\\View\\FileViewFinder->find('errors.custom')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(69): Illuminate\\View\\Factory->make('errors.custom', Array)\n#3 /var/www/html/laravel/admin/app/Exceptions/Handler.php(49): Illuminate\\Routing\\ResponseFactory->view('errors.custom', Array, 403)\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorExce in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 137
[Mon Aug 14 13:04:47.532267 2017] [:error] [pid 1576] [client 127.0.0.1:33254] PHP Fatal error:  Uncaught Symfony\\Component\\HttpKernel\\Exception\\HttpException: Unauthorized action. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:926\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(30): Illuminate\\Foundation\\Application->abort(403, 'Unauthorized ac...', Array)\n#1 /var/www/html/laravel/admin/app/Exceptions/Handler.php(51): abort(403, 'Unauthorized ac...')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\HttpKernel\\Exception\\HttpException))\n#3 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\HttpKernel\\Exception\\HttpException))\n#4 [internal function]: Illuminate\\Foundation\\Bootstrap\\Handl in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Application.php on line 926
[Mon Aug 14 13:04:47.532577 2017] [:error] [pid 1576] [client 127.0.0.1:33254] PHP Fatal error:  Uncaught Symfony\\Component\\HttpKernel\\Exception\\HttpException: Unauthorized action. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:926\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(30): Illuminate\\Foundation\\Application->abort(403, 'Unauthorized ac...', Array)\n#1 /var/www/html/laravel/admin/app/Exceptions/Handler.php(51): abort(403, 'Unauthorized ac...')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Application.php on line 926
[Mon Aug 14 13:05:06.450453 2017] [:error] [pid 4702] [client 127.0.0.1:33272] PHP Fatal error:  Uncaught Symfony\\Component\\HttpKernel\\Exception\\HttpException: Unauthorized action. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:926\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(30): Illuminate\\Foundation\\Application->abort(403, 'Unauthorized ac...', Array)\n#1 /var/www/html/laravel/admin/app/Exceptions/Handler.php(51): abort(403, 'Unauthorized ac...')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\HttpKernel\\Exception\\HttpException))\n#3 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\HttpKernel\\Exception\\HttpException))\n#4 [internal function]: Illuminate\\Foundation\\Bootstrap\\Handl in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Application.php on line 926
[Mon Aug 14 13:05:06.450923 2017] [:error] [pid 4702] [client 127.0.0.1:33272] PHP Fatal error:  Uncaught Symfony\\Component\\HttpKernel\\Exception\\HttpException: Unauthorized action. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:926\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(30): Illuminate\\Foundation\\Application->abort(403, 'Unauthorized ac...', Array)\n#1 /var/www/html/laravel/admin/app/Exceptions/Handler.php(51): abort(403, 'Unauthorized ac...')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Application.php on line 926
[Mon Aug 14 13:05:08.383807 2017] [:error] [pid 1573] [client 127.0.0.1:33278] PHP Fatal error:  Uncaught Symfony\\Component\\HttpKernel\\Exception\\HttpException: Unauthorized action. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:926\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(30): Illuminate\\Foundation\\Application->abort(403, 'Unauthorized ac...', Array)\n#1 /var/www/html/laravel/admin/app/Exceptions/Handler.php(51): abort(403, 'Unauthorized ac...')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\HttpKernel\\Exception\\HttpException))\n#3 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\HttpKernel\\Exception\\HttpException))\n#4 [internal function]: Illuminate\\Foundation\\Bootstrap\\Handl in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Application.php on line 926
[Mon Aug 14 13:05:08.384135 2017] [:error] [pid 1573] [client 127.0.0.1:33278] PHP Fatal error:  Uncaught Symfony\\Component\\HttpKernel\\Exception\\HttpException: Unauthorized action. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:926\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(30): Illuminate\\Foundation\\Application->abort(403, 'Unauthorized ac...', Array)\n#1 /var/www/html/laravel/admin/app/Exceptions/Handler.php(51): abort(403, 'Unauthorized ac...')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Application.php on line 926
[Mon Aug 14 13:05:09.254462 2017] [:error] [pid 1574] [client 127.0.0.1:33286] PHP Fatal error:  Uncaught Symfony\\Component\\HttpKernel\\Exception\\HttpException: Unauthorized action. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:926\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(30): Illuminate\\Foundation\\Application->abort(403, 'Unauthorized ac...', Array)\n#1 /var/www/html/laravel/admin/app/Exceptions/Handler.php(51): abort(403, 'Unauthorized ac...')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\HttpKernel\\Exception\\HttpException))\n#3 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\HttpKernel\\Exception\\HttpException))\n#4 [internal function]: Illuminate\\Foundation\\Bootstrap\\Handl in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Application.php on line 926
[Mon Aug 14 13:05:09.254819 2017] [:error] [pid 1574] [client 127.0.0.1:33286] PHP Fatal error:  Uncaught Symfony\\Component\\HttpKernel\\Exception\\HttpException: Unauthorized action. in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:926\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(30): Illuminate\\Foundation\\Application->abort(403, 'Unauthorized ac...', Array)\n#1 /var/www/html/laravel/admin/app/Exceptions/Handler.php(51): abort(403, 'Unauthorized ac...')\n#2 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(108): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#4 /var/www/html/laravel/admin/vendor/laravel/framework/src in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Application.php on line 926
[Mon Aug 14 13:12:29.593612 2017] [:error] [pid 1577] [client 127.0.0.1:33430] PHP Fatal error:  Uncaught Error: Call to a member function send() on null in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:108\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#2 {main}\n  thrown in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php on line 108
[Mon Aug 14 13:12:29.593793 2017] [:error] [pid 1577] [client 127.0.0.1:33430] PHP Fatal error:  Uncaught Error: Call to a member function send() on null in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:108\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#2 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#3 {main}\n  thrown in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php on line 108
[Mon Aug 14 13:12:31.577650 2017] [:error] [pid 4702] [client 127.0.0.1:33434] PHP Fatal error:  Uncaught Error: Call to a member function send() on null in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:108\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#2 {main}\n  thrown in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php on line 108
[Mon Aug 14 13:12:31.577902 2017] [:error] [pid 4702] [client 127.0.0.1:33434] PHP Fatal error:  Uncaught Error: Call to a member function send() on null in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:108\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#2 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#3 {main}\n  thrown in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php on line 108
[Mon Aug 14 13:12:40.139274 2017] [:error] [pid 1573] [client 127.0.0.1:33440] PHP Fatal error:  Uncaught Error: Call to a member function send() on null in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:108\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#2 {main}\n  thrown in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php on line 108
[Mon Aug 14 13:12:40.139496 2017] [:error] [pid 1573] [client 127.0.0.1:33440] PHP Fatal error:  Uncaught Error: Call to a member function send() on null in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:108\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#2 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#3 {main}\n  thrown in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php on line 108
[Mon Aug 14 13:12:40.781816 2017] [:error] [pid 1574] [client 127.0.0.1:33444] PHP Fatal error:  Uncaught Error: Call to a member function send() on null in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:108\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#2 {main}\n  thrown in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php on line 108
[Mon Aug 14 13:12:40.781977 2017] [:error] [pid 1574] [client 127.0.0.1:33444] PHP Fatal error:  Uncaught Error: Call to a member function send() on null in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:108\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#2 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#3 {main}\n  thrown in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php on line 108
[Mon Aug 14 13:12:54.015394 2017] [:error] [pid 1575] [client 127.0.0.1:33448] PHP Fatal error:  Uncaught Error: Call to a member function send() on null in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:108\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))\n#2 {main}\n  thrown in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php on line 108
[Mon Aug 14 13:12:54.015601 2017] [:error] [pid 1575] [client 127.0.0.1:33448] PHP Fatal error:  Uncaught Error: Call to a member function send() on null in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:108\nStack trace:\n#0 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(85): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#1 /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#2 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#3 {main}\n  thrown in /var/www/html/laravel/admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php on line 108
[Mon Aug 14 17:08:54.890315 2017] [:error] [pid 1597] [client 127.0.0.1:59976] PHP Fatal error:  Cannot redeclare App\\Http\\Controllers\\LogErroController::grid() in /var/www/html/laravel/admin/app/Http/Controllers/LogErroController.php on line 48, referer: http://localhost:3000/role
